### ISSUE TITLE
Address SEO, Meta info

### ISSUE THREAD

**Issue by polarbeardesign** [polarbeardesign/caf_app#13]
Along with Pretty Urls from slugs, figure out best path forward for user-friendly(?) management of SEO and Meta info

**Comment by johnivanoff** [comment]
something sililar too...
<img width="956" alt="screen shot 2018-08-30 at 5 33 28 pm" src="https://user-images.githubusercontent.com/8841/44880600-ee5f2300-ac7a-11e8-9969-2f1694118f91.png">

**Comment by polarbeardesign** [comment]
Probably. Is that page based?

**Comment by johnivanoff** [comment]
yes

**Comment by johnivanoff** [comment]
New and blog posts are shown on the content pages?

**Comment by johnivanoff** [comment]
the rough scope of work:

add columns to content
- keywords
- title
- description
- headline
- location(url/slug)

add fields to content form
- keywords
- title
- description
- headline
- location(url/slug)

create slugs for existing content
create 302 for existing content URLs

add new data to content pages
- https://moz.com/blog/meta-data-templates-123

add schemas for structured data on appropriate pages
- https://schema.org/docs/schemas.html
  - https://schema.org/Event
  - https://schema.org/Organization

**Comment by polarbeardesign** [comment]
Content holds page, partial page* and blog posts.

Partial page is a content block on an otherwise model specific page. Like a blurb about aircraft or the various sections of the home page.

**Comment by polarbeardesign** [comment]
Is 

- Title => Page Title?
- Description => Meta Description?

Would content.title be same as headline? Or do you like to keep them separate just in case? And we have an (as of yet) unused slug column... can it be used for this?

**Comment by johnivanoff** [comment]
the *title* is page title. we can just use the current *title* to also be the page title. I'll start off on that route.
Description => Meta Description => yes.
slug will hold the url.

**Comment by johnivanoff** [comment]
beta version.
<img width="1142" alt="screen shot 2018-09-08 at 11 24 43 am" src="https://user-images.githubusercontent.com/8841/45255766-ecbbec00-b359-11e8-8e99-6d48811e20a9.png">
