### ISSUE TITLE
need a page other than login page for after reset

### ISSUE THREAD

**Issue by johnivanoff** [polarbeardesign/caf_app#17]

**Comment by polarbeardesign** [comment]
I think this part can be closed. After entering email and submit for reset, redirecting to a page explaining reset process

**Comment by polarbeardesign** [comment]
after sending email redirects to /
![password_reset](https://user-images.githubusercontent.com/432600/45055187-b67a2600-b054-11e8-8601-e6036a388246.jpg)
password_reset
