### ISSUE TITLE
Drop down menus on mobile

### ISSUE THREAD

**Issue by polarbeardesign** [polarbeardesign/caf_app#20]
Long drop downs like about seem to cut off bottom choices on iPhone

**Comment by johnivanoff** [comment]
<img width="488" alt="screen shot 2018-09-06 at 8 48 07 am" src="https://user-images.githubusercontent.com/8841/45158312-9b70f880-b1b1-11e8-8a32-4fb28ff96dbc.png">

**Comment by johnivanoff** [comment]
after:
<img width="504" alt="screen shot 2018-09-06 at 9 03 23 am" src="https://user-images.githubusercontent.com/8841/45159426-b6913780-b1b4-11e8-98e7-87a732c73487.png">
