### ISSUE TITLE
hitting return on filter box signs you out

### ISSUE THREAD

**Issue by polarbeardesign** [polarbeardesign/caf_app#7]

**Comment by johnivanoff** [comment]
A form gets submitted when the form is focused on, and the enter key is pressed. The quick answer is the JS to [disable the enter key](https://stackoverflow.com/questions/5629805/disabling-enter-key-for-form) 
A slightly better option is to remove the post action from the form. The form will still submit, but you go right back to the same page.
The better answer is replacing the form with a div.
![screen shot 2018-08-29 at 9 53 25 am](https://user-images.githubusercontent.com/8841/44792521-11ea7680-ab72-11e8-932d-bcd8d367c7e0.png)

This should be done on all *live-search* forms.

**Comment by johnivanoff** [comment]
The live search still works
